SignalR/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SignalR_Core.Models;
using SignalR_Core.ViewModels;

namespace SignalR.Controllers
{
    public class CuentasController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            LoginViewModel login = new LoginViewModel();
            return View(login);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel loginRequest)
        {
            if (ModelState.IsValid)
            {
                var resultado = await _signInManager.PasswordSignInAsync(loginRequest.Email, loginRequest.Password, loginRequest.RemenberMe, lockoutOnFailure: true);

                if (resultado.Succeeded)
                {
                    return LocalRedirect("~/Home/Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "No puedes ingresar tu cuenta, puede deberse a que agregaste mal las credenciales, o que el usuario este bloqueado");
                }
            
            }

            return View(loginRequest);
        }


        [HttpGet]
        public async Task<IActionResult> Register()
        {
            RegisterViewModel register = new RegisterViewModel();
            return View(register);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel regRequest)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuarios()
                {
                    UserName = regRequest.Email,
                    Email = regRequest.Email,
                    Nombre = regRequest.Nombre,
                    Apellido = regRequest.Apellido,
                    Celular = regRequest.Celular
                };

                var resultado = await _userManager.CreateAsync(usuario, regRequest.Password);

                if (resultado.Succeeded)
                {
                    await _signInManager.SignInAsync(usuario, isPersistent: false);
                    return LocalRedirect("~/Home/Index");
                }
            }

            return View(regRequest);

        }

        [HttpPost]
        public async Task<IActionResult> SalirAplicacion()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public IActionResult Bloqueado()
        {
            return View();
        }
        
    }
}

SignalR/Controllers/Gpt4Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using SignalR.Services;
using SignalR_Core.Models;

namespace SignalR.Controllers
{
    public class Gpt4Controller : Controller
    {
        private readonly IAnswerGeneratorServices _answer;

        public Gpt4Controller(IAnswerGeneratorServices answer)
        {
            _answer=answer;
        }
        public IActionResult Index()
        {
            Assistant assistant = new();
            return View(assistant);
        }

        public async Task<IActionResult> GenerarRespuestaGPT4(Assistant request)
        {
            var respuesta = await _answer.GenerateAnswer(request.Prompt);
            return Ok(respuesta);
        }
    }
}

SignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NexoTeck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SignalR.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="home__picture" src="~/RecursosPlantilla/img/imgLogin/logoZoneteck.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item text-white dropdown">
                            <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                PQRS
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="PQRS" asp-action="Solicitudes">Solucitudes</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="PQRS" asp-action="Incidentes">Incidentes</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Chat">
                                Chat privado
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Contacto">
                                Contáctanos
                            </a>
                        </li>
             @*           <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gpt4" asp-action="Index">Gpt4</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Cuentas" asp-action="Register">Registrar Nuevo</a>
                        </li>

                    </ul>
                    <partial name="_LoginRegisterPartialView" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="Footer">
        <div class=" footer__body">
            <ul class="footer__list">
                <li>
                    <a asp-controller="Home" asp-action="Contacto">
                        Contáctanos
                    </a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Chat">
                        Chat
                    </a>
                </li>
            </ul>
            <p class="footer__copy">© 2023 - NexoTeck - Todos los derechos reservados | Web Design By John A. Rios <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SignalR/Views/Shared/_LoginRegisterPartialView.cshtml
@using Microsoft.AspNetCore.Identity;

@inject UserManager<IdentityUser> UserManager;
@inject SignInManager<IdentityUser> SignInManager;


<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-white" href="">Bienvenido @UserManager.GetUserName(User)</a>
        </li>

        <li class="nav-item">
            <form asp-controller="Cuentas" asp-action="SalirAplicacion" method="post" class="form-inline">
                <button class="btn nav-item text-white" type="submit">Cerrar Sesión</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Cuentas" asp-action="Register">Registrar</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Cuentas" asp-action="Login">Login</a>
        </li>       
    }

</ul>